stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: "BloodBankManagementSystem"
  ENVIRONMENT: "Production"

# Build job, only runs on the 'main' branch
build_job:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # Runs only on the main branch
  script:
    - echo "Building $PROJECT_NAME..."
    - mkdir -p build  # Make sure the build folder exists
  artifacts:
    paths:
      - build/  # Save the build output

# Test job to run tests
test_job:
  stage: test
  script:
    - echo "Running tests for $PROJECT_NAME..."
    - mkdir -p test-results  # Make sure the test results folder exists
  artifacts:
    paths:
      - test-results/  # Save the test results
 

deploy_job:
  stage: deploy
  script:
    - echo "Deploying $PROJECT_NAME to $ENVIRONMENT..."
  after_script:
    - echo "Deployment done for $PROJECT_NAME on branch $CI_COMMIT_REF_NAME"
  only:
    - master  # Runs only on the main branch

